import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createClient } from "@/lib/supabase/server"
import {
  SidebarProvider,
} from "@/components/ui/sidebar"
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar";
import { AuthProvider } from "@/provider/auth-provider";
import Providers from "./providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider user={user}>
         
            <SidebarProvider>
              <AppSidebar /> 
                <Providers>
                 {children}
                </Providers> 
            </SidebarProvider>   
        </AuthProvider>     
      </body>
    </html>
  );
}
